# Generated by Django 4.1.7 on 2023-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_info_options_rename_info_info_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default='John Doe', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='roll_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
